FROM openjdk:24-jdk-slim

WORKDIR /app

COPY gradlew .
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradle gradle

RUN /bin/bash -c 'chmod +x ./gradlew ; ./gradlew --version'

COPY src src

CMD ["./gradlew", "build"]

# docker run -v /d/naukma/4/Spring/event-management-system/build/libs:/app/build/libs spring-build:1.0.0
# in cmd