FROM openjdk:24-jdk-slim

COPY ./src /app/src
COPY ./gradlew /app/gradlew
COPY ./build.gradle.kts /app/build.gradle.kts
COPY ./settings.gradle.kts /app/settings.gradle.kts
COPY ./gradle /app/gradle

WORKDIR /app

RUN chmod +x gradlew

RUN ./gradlew --version

CMD ["./gradlew", "build"]