FROM openjdk:24-jdk-slim

COPY ./build/libs/event-management-micro-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 8080

WORKDIR /app

CMD ["java", "-jar", "app.jar"]

# docker run -p 8080:8080 spring-start:1.0.0