FROM openjdk:24-jdk-slim

COPY ./src /app/src
COPY ./gradlew /app/gradlew
COPY ./build.gradle.kts /app/build.gradle.kts
COPY ./settings.gradle.kts /app/settings.gradle.kts
COPY ./gradle /app/gradle

WORKDIR /app

RUN /bin/bash -c 'chmod +x gradlew; ./gradlew --version'

CMD ["./gradlew", "build"]

# docker run -v /d/naukma/4/Spring/event-management-system/build/libs:/app/build/libs spring-build:1.0.0
# in cmd