@startuml
set separator none
title Event

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("EventManagementMicroApplication.EventManagementMicroApplication_boundary", "EventManagementMicroApplication", $tags="") {
  Component(EventManagementMicroApplication.EventManagementMicroApplication.Event, "Event", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml